### ISSUE TITLE
Exception in build

### ISSUE THREAD

**Issue by kennedyshead** [extra84/kivy-buildozer#2]
```
Updated project.properties
Updated local.properties
----------
build.xml: Failed to find version-tag string. File must be updated.
In order to not erase potential customizations, the file will not be automatically regenerated.
If no changes have been made to the file, delete it manually and run the command again.
If you have made customizations to the build process, the file must be manually updated.
It is recommended to:
	* Copy current file to a safe location.
	* Delete original file.
	* Run command again to generate a new file.
	* Port customizations to the new file, by looking at the new rules file
	  located at <SDK>/tools/ant/build.xml
	* Update file to contain
	      version-tag: custom
	  to prevent file from being rewritten automatically by the SDK tools.
----------
Updated file ./proguard-project.txt
It seems that there are sub-projects. If you want to update them
please use the --subprojects parameter.
Traceback (most recent call last):
  File "build.py", line 517, in <module>
    make_package(args)
  File "build.py", line 335, in make_package
    make_tar('assets/private.mp3', ['private', args.private], args.ignore_path)
  File "build.py", line 178, in make_tar
    compile_dir(sd)
  File "build.py", line 82, in compile_dir
    subprocess.call([PYTHON, '-OO', '-m', 'compileall', '-f', dfn])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
# Command failed: python build.py --name **** --version 0.1 --package org.***.*** --sdk 15 --minsdk 9 --private /src/.buildozer/android/app --permission INTERNET --permission CAMERA --permission ACCESS_FINE_LOCATION --permission ACCESS_COARSE_LOCATION --orientation sensor debug
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by Fogapod** [comment]
How did you solve that?
